In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import CountVectorizer as CV
from sklearn.decomposition import LatentDirichletAllocation as LDA
from sklearn.mixture import BayesianGaussianMixture as VBGMM

In [2]:
surf = cv2.xfeatures2d.SURF_create()
class_size = 70
#cls = VBGMM(n_components=200)
cls = KMeans(n_clusters=class_size)

In [3]:
room_arr = []
floor_arr = []
outdoor_arr = []
parking_arr= []

In [4]:
for i in range(140):
    room = cv2.imread("room_"+str(i)+".jpg")
    Groom = cv2.imread("room_"+str(i)+".jpg", 0)

    room_kp, room_desc = surf.detectAndCompute(Groom, None)
    room_descriptors = room_desc.astype(np.float32)

    room_arr.extend(room_descriptors)
#    print("complete "+str(i))

In [5]:
for i in range(101):
    floor = cv2.imread("floor_"+str(i)+".jpg")
    Gfloor = cv2.imread("floor_"+str(i)+".jpg", 0)

    floor_kp, floor_desc = surf.detectAndCompute(Gfloor, None)
    floor_descriptors = floor_desc.astype(np.float32)

    floor_arr.extend(floor_descriptors)
#    print("complete "+str(i))

In [6]:
for i in range(89):#89):
    outdoor = cv2.imread("outdoor_"+str(i)+".jpg")
    Goutdoor = cv2.imread("outdoor_"+str(i)+".jpg", 0)

    outdoor_kp, outdoor_desc = surf.detectAndCompute(Goutdoor, None)
    outdoor_descriptors = outdoor_desc.astype(np.float32)
 
    outdoor_arr.extend(outdoor_descriptors)
#    print("complete "+str(i))

In [7]:
for i in range(62):
    parking = cv2.imread("parking_"+str(i)+".jpg")
    Gparking = cv2.imread("parking_"+str(i)+".jpg", 0)

    parking_kp, parking_desc = surf.detectAndCompute(Gparking, None)
    parking_descriptors = parking_desc.astype(np.float32)

    parking_arr.extend(parking_descriptors)
#    print("complete "+str(i))

In [8]:
print('room',len(room_arr))
print('floor',len(floor_arr))
print('outdoor',len(outdoor_arr))
print('parking',len(parking_arr))

room 794830
floor 434848
outdoor 1474120
parking 1366670


In [9]:
all_arr = []

all_arr.extend(room_arr)
all_arr.extend(floor_arr)
all_arr.extend(outdoor_arr)
all_arr.extend(parking_arr)

len(all_arr)

4070468

In [10]:
cls.fit(all_arr)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=70, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [11]:
labels = cls.predict(all_arr)

In [14]:
print('hellow')

hellow


plt.hist(labels, rwidth=0.8)

print(len(cls.labels_))
print(cls.labels_)

each_arr = []

room_label = cls.predict(room_arr)
room_str =' '.join(map(str, room_label))
each_arr.append(room_str)
print('comlete room')

floor_label = cls.predict(floor_arr)
floor_str =' '.join(map(str, floor_label))
each_arr.append(floor_str)
print('complete floor')

outdoor_label = cls.predict(outdoor_arr)
outdoor_str =' '.join(map(str, outdoor_label))
each_arr.append(outdoor_str)
print('complete outdoor')

parking_label = cls.predict(parking_arr)
parking_str =' '.join(map(str, parking_label))
each_arr.append(parking_str)
print('complete parking')


print(len(each_arr))

-----------------------------------------------------------------------------

In [15]:
data = labels#cls.labels_

In [ ]:
print(type(data))
print(len(data))

In [16]:
data
data_str_trans =' '.join(map(str, data))
print(len(data_str_trans))
print(len(data))

11568578
4070468


print(len(each_arr[0]))

each_str =' '.join(map(str, each_arr[0]))
#print(each_arr[0])
#print(each_str)

each_str_trans=[]
for i in range(4):
    each_str =' '.join(map(str, each_arr[i]))
    each_str_trans.append(each_str)
print(len(data_str_trans))
print(len(data))

data_trans = str(data)
print(len(data))
print(len(data_trans))
data_trans

In [17]:
cv = CV(token_pattern='\\b\\w+\\b')
cved = cv.fit([data_str_trans])
cved_transfrom = cved.transform([data_str_trans])
print(cv)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='\\b\\w+\\b', tokenizer=None,
                vocabulary=None)


In [18]:
cv.get_feature_names()

['0',
 '1',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '2',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '3',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '4',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '5',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '6',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '7',
 '8',
 '9']

In [19]:
lda = LDA(n_components=4,learning_method='online', max_iter=20)
lda = lda.fit(cved_transfrom)

In [20]:
features = cv.get_feature_names()

for topic in range(4):
    print("topic", topic)
    number_of_topic = lda.components_[topic] 
    word = ','.join(features[i] for i in number_of_topic.argsort()[:-18-1:-1])
    print(word, "\n")

topic 0
66,10,0,40,45,48,6,5,7,15,16,36,9,14,3,63,34,30 

topic 1
10,66,36,45,44,24,35,4,26,9,14,48,6,16,28,12,40,18 

topic 2
66,10,48,40,7,37,26,36,14,16,49,4,5,38,32,17,6,61 

topic 3
10,66,18,3,14,0,36,4,40,31,49,26,45,24,60,48,21,34 



cv = CV(token_pattern='\\b\\w+\\b')
cved = cv.fit(['each_str_trans'])
cved_transfrom = cved.transform(['each_str_trans'])
print(cv)

----------------------------------------------------------------

In [39]:
test_data = []

In [40]:
room_1 = cv2.imread("test__flip_0.jpg")
Groom_1 = cv2.imread("test_flip_0.jpg", 0)

room_2 = cv2.imread("test_flip_1.jpg")
Groom_2 = cv2.imread("test_flip_1.jpg", 0)

room_3 = cv2.imread("test_flip_2.jpg")
Groom_3 = cv2.imread("test_flip_2.jpg", 0)

test_room_kp, test_room_desc = surf.detectAndCompute(Groom_1, None)
test_room_descriptors = test_room_desc.astype(np.float32)

test_room_label = cls.predict(test_room_descriptors)
test_data.append(test_room_label)

test_room_kp, test_room_desc = surf.detectAndCompute(Groom_2, None)
test_room_descriptors = test_room_desc.astype(np.float32)

test_room_label2 = cls.predict(test_room_descriptors)
test_data.append(test_room_label2)

test_room_kp, test_room_desc = surf.detectAndCompute(Groom_3, None)
test_room_descriptors = test_room_desc.astype(np.float32)

test_room_label3 = cls.predict(test_room_descriptors)
test_data.append(test_room_label3)

In [41]:
floor_1 = cv2.imread("test_flip_3.jpg")
Gfloor_1 = cv2.imread("test_flip_3.jpg", 0)

floor_2 = cv2.imread("test_flip_4.jpg")
Gfloor_2 = cv2.imread("test_flip_4.jpg", 0)

floor_3 = cv2.imread("test_flip_5.jpg")
Gfloor_3 = cv2.imread("test_flip_5.jpg", 0)

test_floor_kp, test_floor_desc = surf.detectAndCompute(Gfloor_1, None)
test_floor_descriptors = test_floor_desc.astype(np.float32)

test_floor_label = cls.predict(test_floor_descriptors)
test_data.append(test_floor_label)

test_floor_kp, test_floor_desc = surf.detectAndCompute(Gfloor_2, None)
test_floor_descriptors = test_floor_desc.astype(np.float32)

test_floor_label2 = cls.predict(test_floor_descriptors)
test_data.append(test_floor_label2)

test_floor_kp, test_floor_desc = surf.detectAndCompute(Gfloor_3, None)
test_floor_descriptors = test_floor_desc.astype(np.float32)

test_floor_label3 = cls.predict(test_floor_descriptors)
test_data.append(test_floor_label3)

In [42]:
outdoor_1 = cv2.imread("test_flip_6.jpg")
Goutdoor_1 = cv2.imread("test_flip_6.jpg", 0)

outdoor_2 = cv2.imread("test_flip_7.jpg")
Goutdoor_2 = cv2.imread("test_flip_7.jpg", 0)

outdoor_3 = cv2.imread("test_flip_8.jpg")
Goutdoor_3 = cv2.imread("test_flip_8.jpg", 0)

test_outdoor_kp, test_outdoor_desc = surf.detectAndCompute(Goutdoor_1, None)
test_outdoor_descriptors = test_outdoor_desc.astype(np.float32)

test_outdoor_label = cls.predict(test_outdoor_descriptors)
test_data.append(test_outdoor_label)

test_outdoor_kp, test_outdoor_desc = surf.detectAndCompute(Goutdoor_2, None)
test_outdoor_descriptors = test_outdoor_desc.astype(np.float32)

test_outdoor_label2 = cls.predict(test_outdoor_descriptors)
test_data.append(test_outdoor_label2)

test_outdoor_kp, test_outdoor_desc = surf.detectAndCompute(Goutdoor_3, None)
test_outdoor_descriptors = test_outdoor_desc.astype(np.float32)

test_outdoor_label3 = cls.predict(test_outdoor_descriptors)
test_data.append(test_outdoor_label3)

In [43]:
parking_1 = cv2.imread("test_flip_9.jpg")
Gparking_1 = cv2.imread("test_flip_9.jpg", 0)

parking_2 = cv2.imread("test_flip_10.jpg")
Gparking_2 = cv2.imread("test_flip_10.jpg", 0)

parking_3 = cv2.imread("test_flip_11.jpg")
Gparking_3 = cv2.imread("test_flip_11.jpg", 0)

test_parking_kp, test_parking_desc = surf.detectAndCompute(Gparking_1, None)
test_parking_descriptors = test_parking_desc.astype(np.float32)

test_parking_label = cls.predict(test_parking_descriptors)
test_data.append(test_parking_label)

test_parking_kp, test_parking_desc = surf.detectAndCompute(Gparking_1, None)
test_parking_descriptors = test_parking_desc.astype(np.float32)

test_parking_label2 = cls.predict(test_parking_descriptors)
test_data.append(test_parking_label2)

test_parking_kp, test_parking_desc = surf.detectAndCompute(Gparking_2, None)
test_parking_descriptors = test_parking_desc.astype(np.float32)

test_parking_label3 = cls.predict(test_parking_descriptors)
test_data.append(test_parking_label3)

In [44]:
test_data
test_data_trans=[]
for i in range(12):
    transed =' '.join(map(str, test_data[i]))
    test_data_trans.append(transed)

print(len(test_data_trans))
print(len(test_data_trans[1]))

12
12777


-----------------------

In [100]:
cv_ed = cv.fit(test_data_trans)
test_transfrom = cved.transform(test_data_trans)

In [113]:
#推定リセット用ショートカット
lda = LDA(n_components=4,learning_method='batch', max_iter=100)
lda = lda.fit(cved_transfrom)

In [114]:
lda_test1 = lda.transform(test_transfrom)

In [115]:
for i,lda in enumerate(lda_test1):
    print("### ",i)
    topicid=[i for i, x in enumerate(lda) if x == max(lda)]
    #print(test_data_trans[i])
    print("\nScore\n", lda)
    print(" >>> topic",topicid)
    print("")

###  0

Score
 [0.00863118 0.49797128 0.06898385 0.42441369]
 >>> topic [1]

###  1

Score
 [0.02077921 0.54081099 0.2800571  0.15835269]
 >>> topic [1]

###  2

Score
 [0.02412256 0.10021171 0.43709263 0.4385731 ]
 >>> topic [3]

###  3

Score
 [0.0023291  0.21405094 0.13731869 0.64630126]
 >>> topic [3]

###  4

Score
 [0.01128391 0.09302951 0.41281316 0.48287342]
 >>> topic [3]

###  5

Score
 [0.00064267 0.37198316 0.04448859 0.58288558]
 >>> topic [3]

###  6

Score
 [0.38127501 0.22364306 0.31997802 0.0751039 ]
 >>> topic [0]

###  7

Score
 [0.54127601 0.19381276 0.23401475 0.03089648]
 >>> topic [0]

###  8

Score
 [0.07539751 0.28337382 0.39318715 0.24804152]
 >>> topic [2]

###  9

Score
 [0.56640728 0.0708677  0.31342243 0.04930259]
 >>> topic [0]

###  10

Score
 [0.56640728 0.0708677  0.31342243 0.04930259]
 >>> topic [0]

###  11

Score
 [0.46289506 0.07162305 0.42898151 0.03650038]
 >>> topic [0]



In [54]:
features = cv.get_feature_names()

for topic in range(4):
    print("topic", topic)
    number_of_topic = lda.components_[topic] 
    word = ','.join(features[i] for i in number_of_topic.argsort()[:-18-1:-1])
    print(word, "\n")

topic 0
141,153,120,112,28,181,100,69,98,41,67,195,142,115,105,53,76,184 

topic 1
141,120,153,115,181,105,184,112,168,98,41,28,62,67,164,92,100,185 

topic 2
120,141,112,181,23,153,62,184,105,115,142,100,172,177,103,28,98,76 

topic 3
141,120,181,115,112,28,153,100,168,23,103,76,92,184,105,62,44,41 

